### ISSUE TITLE
The installation does not show up when trying to install in the new minecraft launcher

### ISSUE THREAD

**Issue by Gilhose** [SkyblockClient/SkyblockClient#16]

**Comment by Rinkimiru** [comment]
It does not show for me either, it does not show any of my installations, :u i redownloaded it but it does not work, if someone replies to this i will be very thankful :D

**Comment by BlueBeacon1244** [comment]
same with me :\

**Comment by Mohith7143** [comment]
same with me

**Comment by Gilhose** [comment]
if any of you still have the old minecraftinstaller.msi in your download files then you can install that and then you have the old minecraft launcher again and there is no problems

**Comment by Rinkimiru** [comment]
> if any of you still have the old minecraftinstaller.msi in your download files then you can install that and then you have the old minecraft launcher again and there is no problems

thank you very much :DDD frick mojang for updating it anyways lol

**Comment by Wellliam** [comment]
I have the same issue. I try reinstalling it over and over again, and all i get is Minecraft forge 1.8.9 in the instalations menu.

**Comment by Wellliam** [comment]
> same with me :\

![image](https://user-images.githubusercontent.com/80104186/142029002-736d3720-6d9e-4621-bc71-d0fdb092846a.png)
This is from the discord server btw

**Comment by nacrt** [comment]
hello! if you have any issues, please check by the discord as i don't check this page very often!
as Wellliam pointed out already, the fix is within the image
