### ISSUE TITLE
can we download skyclient in mac??

### ISSUE THREAD

**Issue by VibraniumFalcon** [SkyblockClient/SkyblockClient#20]
can I download sky client in Mac???

**Comment by MightiestTaco** [comment]
yes the link is right here https://github.com/koxx12-dev/Skyclient-installer-Java/releases/tag/1.0.3.1
theres also the forum post here https://hypixel.net/threads/skyclient-easily-install-and-update-skyblock-mods-and-packs.3731617/

**Comment by nacrt** [comment]
resolved
