### ISSUE TITLE
It's suddenly totally messing with my game Profiles and not adding itself correctly

### ISSUE THREAD

**Issue by miel8** [SkyblockClient/SkyblockClient#22]
Well, yeah. It does open and stuff, but if i then install it, my Game profiles are completely messed up and it adds itself twice - with only name and version but not the icon. If I then continue to start it, its just normal plain forge with no mods installed.. I don't know why this is, since it previously worked perfectly. (oh and it doesn't matter what version I use). Does anyone have help?

**Comment by miel8** [comment]
UPDATE: It does actually install the mods, the profile is just not created correctly. And it still messes with other profiles...

**Comment by nacrt** [comment]
resolved
