### ISSUE TITLE
game doesnt launch at all 

### ISSUE THREAD

**Issue by bdndnrne** [SkyblockClient/SkyblockClient#25]
![image](https://user-images.githubusercontent.com/75170408/155681341-959f476d-4653-4ea0-abd8-053024fa57cf.png)
 what is going on

**Comment by EthanDevelops** [comment]
Join the discord and make a ticket in #support

**Comment by EthanDevelops** [comment]
https://discord.gg/featherclient

**Comment by afkvido** [comment]
@EthanDevelops This is literally for SkyblockClient the good skyblock client, **not** the virus scam pirate "feather" client.

**Comment by Zetvue** [comment]
Have you considered joining our [discord](https://inv.wtf/skyclient)?
The issues repository is meant for the installer only. We cannot help you here.

**Comment by afkvido** [comment]
lmao
