### ISSUE TITLE
Relicensing SkyblockClient to MIT

### ISSUE THREAD

**Issue by Wyvest** [SkyblockClient/SkyblockClient#33]
*text partially taken from https://github.com/Polyfrost/OverflowAnimations/issues/8*

We previously did not license this repository. Hence, the code in this repository has a de facto license of "All Rights Reserved". When asked, we give people free usage of our code; however, the ARR license still restricts us from OSS benefits. Hence, we would like to relicense this repository, including your code, under the MIT License.

If you are mentioned below, we need your help to relicense this repository, as you are a copyright holder of your contributed code.

## Making it happen

To make it happen, please comment on this issue with the following:

`I license past and future contributions under the MIT License, as published by SPDX at <https://spdx.org/licenses/MIT.html>`

## Contributor checklist

- [x] @nacrt 
- [x] @koxx12-dev 
- [x] @Wyvest 
- [x] @afkvido 
- [x] @MicrocontrollersDev 
- [x] @KTibow 
- [x] @Weigurde

**Comment by Wyvest** [comment]
I license past and future contributions under the MIT License, as published by SPDX at <https://spdx.org/licenses/MIT.html>

**Comment by koxx12-dev** [comment]
I license past and future contributions under the MIT License, as published by SPDX at <https://spdx.org/licenses/MIT.html>

**Comment by afkvido** [comment]
I license past and future contributions under the MIT License, as published by SPDX at <https://spdx.org/licenses/MIT.html>

**Comment by Weigurde** [comment]
I license past and future contributions under the MIT License, as published by SPDX at <https://spdx.org/licenses/MIT.html>

**Comment by nacrt** [comment]
I license past and future contributions under the MIT License, as published by SPDX at <https://spdx.org/licenses/MIT.html>

**Comment by nacrt** [comment]
it's weird how i have to do that

**Comment by koxx12-dev** [comment]
waffle man its done
