### ISSUE TITLE
skyclient not working

### ISSUE THREAD

**Issue by damas-12** [SkyblockClient/SkyblockClient#44]
after choosing the mods i want i open the launcher and starts the skyclient version but its always showing error. it is saying "unable to prepare assets to download"
![image_2023-12-20_174249730](https://github.com/SkyblockClient/SkyblockClient/assets/154432373/6b884dd5-b5e1-4dcc-b94f-899b5dfe4511)

**Comment by Wyvest** [comment]
Please make a ticket at https://inv.wtf/skyclient
